os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: ToAf/uKWIbUcrvOD7NFVDBYk/zvi8okq8h97eOGjM7lL01ad0JGFwW9quhTq+UepRSl8CAWPR5rptLcnKO0pZ2+6wIqFjcnKxp748oJlH7/FFhpVSsASXWUyTlMwXsjGLaxgNKJueNGQrhQ6haPFXwiWNAZl/CfikGQ6h6zDwqnouQt/RuQd/Y+N9YQkC315qwG1IbLPZ1Jhfzi22vZMAtNS2SeCc3jaD9oo340AHOUyI/ubjEC01MuDoVRgeq3TR+EhfAU6rct4kl/homkiC7Bps2KL4o0ar0uzGeS2V1TwHb6iThydVtl4SLqErpGi8yMYygcvGRaNKvC2VhzODh/TfRvgk/xgcVp8aZuTueJgMe9/69D+v8UTXA0HDIgZdp3fqYEfz0iTbYBPANnygyI6cBfdU6ApHJTUmEdkfY2KRs15Dna03dtyxQuHWCDHlMWcuHXAVUZnSjLr1rB/BcNtwnfkTki/DWHr2J87+nbUr8Y+ru1MVZCSxu5pChyeLSShwdGX9JWnsVC0Rd8sPMSMkpVeb2CCcK6qQ/kBp2A4SNujaSRmfqzNhi4Khr3yUYiLGHpSSJotdu0J+JLy8YN+OFkrAPVRD5qgsq0o3PLPHQzNE0uaR8yMQpkN62odpQyUytj4/DKXIvzVY7Occ5Qen+vvj7eMIzB/9xq3cbU=
  - secure: m1YX2Q0P0agDEae/riMoCGsXAciIwl38uHqpmwBmxRor/uYdtgySCbDKUHdE9qWi48RnNO6Y4/S20fxWG/vGcc2Ng+tVF9ctcnMvRjl0yJeWFGVYpXaGYIXRyp0c+eDPo1vCbDHIDxAaWzzjt4ElsB+n2OGBwJMdL1tcJ4ZjWuxTU31WxpXLdjdG+/SRw7YTjWaV/GleUmH63BQCGebf9SBAypf3DvBNlfyrW3heVLHOyTbq+m//cKByeks/armhDXJPp7fNvUW7fAsyr6Php2T/3Gd+4ScZBtU/phI5T6U7bCuRNGBTAH8mLZTYnf37CttFm5HCQ4xnQaArF1pEgwnif3kCGezXHuqdqllN2fiLDlLnfVE1RselRURQZZAi40tD6tbatcCdZgktxt2f4tyLpP0QEaVlilr+qn4zzndQFjA4vt7IfOtuXmoU7+3HkffH5ZKnykXhvhoUNLC7SjAWEXzhTAOCAIqIRiPUM005BVwL6Nm9RgQvSVuQCpxoD2KcWyxlKWGAFYJovJne9P1kJ9bkoDvRk5QHiAmKDDpAakqymkXW5hxl2vKOYTPAZcXA8138yG1ov/n6Nlub4yg6PsO7mEXArWdd3TMI4IN19caE/mz1SWoyLi1DgEe4cn5sPOgAuEdWbkYDyKR1HBBuArugv0CVHCqMXcMR8xE=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
